# Notes:
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}


#---------------------------------#
#    environment configuration    #
#---------------------------------#

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf true


#---------------------------------#
#       build configuration       #
#---------------------------------#

# build Configuration, i.e. Debug, Release, etc.
configuration: Package

# scripts to run before build
before_build:
  - cmd: nuget restore

build:
  verbosity: minimal               # MSBuild verbosity level

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: 1.0.0.0
  assembly_file_version: 1.0.0.0
  assembly_informational_version: '{version}'

nuget:
  project_feed: true


#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: Autofac.Extras.Alternatives.Package\bin\Package\Autofac.Extras.Alternatives.*.nupkg